---
title: "BIOL 210 Course Agenda"
date: "Week 1, Aug 27-29"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---

# Reminders

* Please complete the [Getting to Know You](https://docs.google.com/forms/d/e/1FAIpQLScaPNVaX_waXgLUrAUYxIhIfUrhzBsRnpT38HXaxLQhJMlkxQ/viewform?usp=sf_link) form by Sat Aug 30.

* Remember to complete your [grade contract](https://docs.google.com/forms/d/e/1FAIpQLScJdD7yO7pAEkugUMRwGvSrYl5syahIyh271SzR2fy_mscIfA/viewform?usp=sf_link) by Wed Sep 3. Submit via the Assignment Turn-in link above.

* BIOL 211 Lab will begin next week, Tue Sep 2 and Wed Sep 3. Lab meets in K119. 

* **The first [problem set is available](ps1.html) and is due Sat Aug 30. You will also want to watch the week 1 content videos (see [agenda week 1](agenda-week1.html)).**

* **Quiz 1 will be due Fri Sep 5, at the same time as Quiz 2. Teams will work together on revisions in class on 9/5.**

# Content Videos

* [01-Biodiversity](https://drive.google.com/drive/folders/13zUXCk4qz2xeb_P53ceg8WtmSEPc9tcy?usp=drive_link)

* [02-Phylogenies](https://drive.google.com/drive/folders/14-ijnaXDxYKokx68eg-DHR0UBlYE_Y66?usp=drive_link)

* [03-Cells](https://drive.google.com/drive/folders/15Eokt5lZOLyt9BOrzobP-NeSGSV5MgeP?usp=drive_link)

# Assignments

[Problem Set 1](ps1.html) is due Sat Aug 30. It is beneficial for you to complete the content videos and begin assignments before the week of class. 

[Quiz 1](https://docs.google.com/forms/d/e/1FAIpQLSclHEk-m9EhZvut1CZE3PJMxdoBZuJkcr-QTfRjAFbJAB4t5A/viewform?usp=sf_link) is due Fri Sep 5 at 9:00am (before class).

# Class Meetings

## Wednesday Aug 27

-   First day of class -- go over syllabus, teaching philosophy, course expectations.

-   [Link to slides](https://drive.google.com/drive/folders/17Fm-yEXqtlvGJfFaw6WqywIScW_eZ8m_?usp=drive_link) Requires you to log into your Oberlin account to access.

-   GRADE CONTRACTS: Read this part of the syllabus carefully before filling out the [Grade Contract Form](https://docs.google.com/forms/d/e/1FAIpQLScJdD7yO7pAEkugUMRwGvSrYl5syahIyh271SzR2fy_mscIfA/viewform?usp=sf_link) with your due dates and other info. You are welcome to consult with Angie before submitting your contract. Contracts should be submitted by Wednesday Sept 3rd, end of day.

-   Please fill out the [Getting to Know You](https://docs.google.com/forms/d/e/1FAIpQLScaPNVaX_waXgLUrAUYxIhIfUrhzBsRnpT38HXaxLQhJMlkxQ/viewform?usp=sf_link) form before Sat 8/30.

-   Note: I recommend you watch the videos for next week before Wed 9/3 (see [Week 2 agenda](agenda-week02.html)).

## Friday Aug 29

Begin case study "A Tale of Three Lice".

### Groups for first month

For the first month, these will be your assigned groups. **You should sit in a cluster with these folks each day that class meets.** Note: This year's first team theme is carnivores of North America.

* <b>Foxes:</b> Grant, Dylan, Cash, Toby
* <b>Bears:</b> Milo, Bethany, Skylar, Shay
* <b>Badgers:</b> Aurora, Cleo, Micah, Madeleine
* <b>Bobcats:</b> Amy, Michael, Kylie, Arianna
* <b>Lynx:</b> Solomon, Julia, Hailey, Matthew
* <b>Cougars:</b> Ella, Ava, Gabriel, Danica
* <b>Wolves:</b> Jeffrey, Lex, Koosh, Nina
* <b>Martens:</b> Aimee, Oliver, Charlotte, Piers
* <b>Weasels:</b> Natalie, Maddie, Chase, Bea
* <b>Coyotes:</b> Devyn, Gabriela, Jarrod, Soomin
* <b>Otters:</b> Griffin, Sophia, Mana, Liam
* <b>Wolverines:</b> Amelia, Kristina, Riley, Iris
